name: credit_card_form_validator
description: Flutter Credit/Debit Card Form with validation.
version: 0.0.8
homepage: https://github.com/edhima/credit_card_form_validator.git

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - images/
