name: Publish plugin

on:
  release:
    types: [created]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        
      - name: 'Flutter pub publish'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.DART_CREDENTIAL }}
